---
title: "Multitrait Multimethod matrix"
author: "Anne-Flore Cabouat"
date: "2024-03-07 - edit 2024-06-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#set wordking directory
my_dir <- "C:/Users/Anne-Flore/git/PREVis-scales/research code/3 - Instrument validation/"
# my_dir <- "your_data_directory" #eg: "absolute_path_to/Supplementary-material-folder/3 - Scale validation/"
knitr::opts_knit$set(root.dir = paste(my_dir, "Results/Data_Analysis", sep=""))

```

## Librairies

```{r librairies}
library(psych)
library(rmcorr)
library(dplyr)
library(corrplot) #plot correlation matrix
library(RColorBrewer) #for correlation matrix
```
## Functions
```{r functions}

make_rm_corrM <- function(d, v, order = NULL){

  ### FOR REPEATED MEASURES
  return(rmcorr_mat(participant = "seed",
                    variables = v,
                    dataset = d))


}

make_corrM <- function(d, v, order = NULL){
  
  ## FOR INDEPENDANT SAMPLES
  if (anyNA(d)){
  # Multiple imputation using Fully Conditional Specification (FCS) implemented by the MICE algorithm as described in Van Buuren and Groothuis-Oudshoorn (2011) doi:10.18637/jss.v045.i03
  #run MICE and generate covariance matrix with with mifa package
  mi <- invisible(mifa(
  data      = d, 
  n_pc      = nb_fa, #factors estimates
  ci        = "fieller", #confidence interval method
  print     = FALSE,
  m = 5 #number of MICE iterations
  ))
  
  corr_MICE <- cov2cor(mi$cov_combined)
  
  if (length(order)>0){
    corrM_reorder <- corr_MICE[order, order]
    corr_MICE <- corrM_reorder
  }
  
  # corrM <- corFiml(d)
  return(corr_MICE)} else {
    return(cor(d))
  }


}

corrM_to_file <- function (d, name, filename, variables, font_size = 1, type = "rm"){
  if(type == "rm"){
    corrM_rm <- make_rm_corrM(d, variables)
    corrM <- corrM_rm$matrix
    corrM_df <- as.data.frame(corrM)
    title <- "Repeated Measures"
  }
  else if(type == "im"){
    corrM <- make_corrM(d)
    corrM_df <- corrM
    title <- "Independent Measures"
  }
  
  print(corrM)

  #as csv
  write.csv(corrM_df,file=paste("MTMM_analysis/MTMM_", filename, "_", type, ".csv", sep=""))

  # as pdf
  pdf(paste("MTMM_analysis/MTMM_", filename, "_", type, ".pdf", sep=""), height=15, width=15)


  plot <- corrplot(corrM,
                  is.corr=TRUE,
                  title=paste(title, "- Mutli-traits multi-method",name),
                  mar = c(0, 0, 1, 0),
                  tl.srt = 30, #rotate text labels
                  method="color",
                  col = COL2('RdYlBu'),
                  cl.cex = font_size,
                  cl.pos = 'b', #legend pos
                  order="original",
                  tl.col="black", tl.cex = font_size, # Text label color and size
                  addCoef.col = "black", number.cex = font_size, # Add coefficient of correlation and size
  )
  print(plot)
  dev.off()
  
  # as pdf mixed representation
  pdf(paste("MTMM_analysis/MTMM_", filename, "-mixed_display_", type,".pdf", sep=""), height=15, width=15)
  corrplot.mixed(corrM,
                 title=paste(title, "- Mutli-traits multi-method",name),
                 mar = c(0, 0, 1, 0),
                 upper = 'number',
                 number.cex = font_size,
                 lower = 'color',
                 cl.cex = font_size, 
                 # cl.pos = 'b', #legend pos ! does not work in mixed displays
                 tl.pos = 'l', #text labels pos
                 tl.srt = 30, #rotate text labels
                 tl.col="black", #text label color
                 tl.cex = font_size, # Text label size,
                 order='original')
  print(plot)
  dev.off()

}



```

## Load data

```{r load data}
stimuli_letters <- list("A","B","C")
full_data <- read.csv(paste("full_answers_by_stimuli.csv"), encoding="UTF-8")

# and make directories if needed

if (!dir.exists("MTMM_analysis/")) {
  dir.create("MTMM_analysis/", recursive = TRUE)
}

```


# MTMM matrix at the item level
```{r MTMM matrix at the item level}

All_traits <- list(
  understand = c("obvious","represent","understandEasi"),
  layout = c("messi", "crowd","distract"),
  dataRead = c("inform","identifi","find"),
  dataFeat = c("visibl","see"),
  extraversion = c("extravert","reserved"),
  greadability = c("crossing","crossingAngle","angularResolutionMin","angularResolutionDev")
)

file = "full_items_correlations"
variables <- unlist(All_traits)
columns_to_keep <- append(variables, "seed")
measurements_im <- full_data[, variables]
measurements_rm <- full_data[, columns_to_keep]

corrM_to_file(measurements_im, "- Individual items", file, variables, type = "im")
corrM_to_file(measurements_rm, "- Individual items", file, variables, type = "rm")

#corrM <- make_corrM(measurements, variables)
#corrM_matrix <- corrM$matrix
#corrM_df <- as.data.frame(corrM_matrix)


```

# MTMM matrix at the scale level

```{r MTMM matrix at the scale level}

Averages_traits <- list(
  understand = c("Understand_average"),
  layout = c("Layout_average"),
  dataRead = c("DataRead_average"),
  dataFeat = c("DataFeat_average"),
  extraversion = c("Extraversion_average"),
  greadability = c("Greadability_average")
)

file = "scale_averages_correlations"
variables <- unlist(Averages_traits)
columns_to_keep <- append(variables, "seed")

measurements_im <- full_data[, variables]
measurements_rm <- full_data[, columns_to_keep]

corrM_to_file(measurements_im, "- Scales averages", file, variables, font_size = 2, type = "im")
corrM_to_file(measurements_rm, "- Scales averages", file, variables, font_size = 2, type = "rm")

```
